version: '3.8'

name: masclet-imperi

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "${LOG_MAX_SIZE:-10m}"
    max-file: "${LOG_MAX_FILE:-3}"

services:
  db:
    image: postgres:17
    container_name: masclet_imperi_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: masclet_imperi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
      - ./docker/postgres/init:/docker-entrypoint-initdb.d:ro
      - ./docker/postgres/logs:/var/log/postgresql
      - ./docker/postgres/backups:/backups
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - masclet_network

  redis:
    image: redis:alpine
    container_name: masclet_imperi_cache
    restart: unless-stopped
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - masclet_network

networks:
  masclet_network:
    name: masclet_network
    driver: bridge

volumes:
  postgres_data:
    name: masclet_imperi_data
  redis_data:
    name: masclet_imperi_cache