version: '3.8'

services:
  db:
    image: postgres:17
    container_name: masclet_imperi_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: masclet_imperi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
      - ./docker/postgres/logs:/var/log/postgresql
      - ./docker/postgres/backups:/backups
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

volumes:
  postgres_data:
    name: masclet_imperi_data
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/docker/postgres/data
      o: bind